Class Template.Production.TemplateProduction Extends Ens.Production
{

XData ProductionDefinition
{
<Production Name="Template.Production.TemplateProduction" LogGeneralTraceEvents="false">
  <Description></Description>
  <ActorPoolSize>2</ActorPoolSize>
  <Item Name="Template.Service.Common" Category="" ClassName="Template.Service.Common" PoolSize="0" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
  <Item Name="Template.Operations.Common" Category="" ClassName="Template.Operations.Common" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
  <Item Name="Template.Processes.Common" Category="" ClassName="Template.Processes.Common" PoolSize="1" Enabled="true" Foreground="false" Comment="" LogTraceEvents="false" Schedule="">
  </Item>
</Production>
}

}

